### ISSUE TITLE
Not able to install vcf2multialign ?

### ISSUE THREAD

**Issue by sunnyEV** [tsnorri/vcf2multialign#2]
HI
Unable to install, I installed llvm and clang, suggestions!
 **make -j4**
make -C lib/libbio
rm -f -rf lib/swift-corelibs-libdispatch/build && \
cd lib/swift-corelibs-libdispatch && \
mkdir build && \
cd build && \
cmake \
	-G Ninja \
	-DCMAKE_C_COMPILER="clang-6.0" \
	-DCMAKE_CXX_COMPILER="clang++-6.0" \
	-DCMAKE_C_FLAGS="-U__STDC_HOSTED__ -isystem /usr/lib/llvm-6.0/lib/clang/6.0.0/include" \
	-DCMAKE_CXX_FLAGS="-U__STDC_HOSTED__ -isystem /usr/lib/llvm-6.0/lib/clang/6.0.0/include" \
	-DBUILD_SHARED_LIBS=OFF \
	.. && \
ninja -v
make[1]: Entering directory '/home/soft4/vcf2multialign/lib/libbio'
make -C src all
make[2]: Entering directory '/home/soft4/vcf2multialign/lib/libbio/src'
ragel -L -C -G2 -o fasta_reader.cc fasta_reader.rl
clang++-6.0 -c -fblocks -U__STDC_HOSTED__ -isystem /usr/lib/llvm-6.0/lib/clang/6.0.0/include -std=c++17 -O2 -g -Wall -Werror -Wno-deprecated-declarations -Wno-unused    -I/usr/include -I../include -I../lib/GSL/include -I../lib/range-v3/include -I../../swift-corelibs-libdispatch -o file_handling.o file_handling.cc
clang++-6.0 -c -fblocks -U__STDC_HOSTED__ -isystem /usr/lib/llvm-6.0/lib/clang/6.0.0/include -std=c++17 -O2 -g -Wall -Werror -Wno-deprecated-declarations -Wno-unused    -I/usr/include -I../include -I../lib/GSL/include -I../lib/range-v3/include -I../../swift-corelibs-libdispatch -o progress_bar.o progress_bar.cc
make[2]: ragel: Command not found
../common.mk:53: recipe for target 'fasta_reader.cc' failed
make[2]: *** [fasta_reader.cc] Error 127
make[2]: *** Waiting for unfinished jobs....
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/soft4/vcf2multialign/lib/swift-corelibs-libdispatch/build/CMakeFiles/CMakeOutput.log".
Makefile:69: recipe for target 'lib/swift-corelibs-libdispatch/build/src/libdispatch.a' failed
make: *** [lib/swift-corelibs-libdispatch/build/src/libdispatch.a] Error 1
make: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/soft4/vcf2multialign/lib/libbio/src'
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/soft4/vcf2multialign/lib/libbio'
Makefile:66: recipe for target 'lib/libbio/src/libbio.a' failed
make: *** [lib/libbio/src/libbio.a] Error 2

**Comment by tsnorri** [comment]
Hi! To build vcf2multialign you need [Ragel state machine compiler](http://www.colm.net/open-source/ragel/) as well. I’ve made some [binaries available](https://github.com/tsnorri/vcf2multialign/releases), though, so you could also download one of them. On a side note, I’ve been [working on some improvements](https://github.com/tsnorri/vcf2multialign/tree/separate-vcf-parser) but they are still somewhat work in progress.
